<a href="https://colab.research.google.com/github/MJavadZallaghi/itmemaut/blob/main/itmemaut4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
# [1 2 3
#  4 5 6]

In [ ]:
m = np.ones(10)

In [ ]:
m

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
m.shape

(10,)

In [ ]:
a = np.ones((3,4), dtype=float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
b[b==2] #boolean inexing

array([2])

In [ ]:
c = np.eye(10, 8, k=4, dtype=int)
c

array([[0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
d = np.reshape(b, (3,2))
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d[0,0]

1

In [ ]:
d[0][0]

1

In [ ]:
e = [[1,2],[3,4]]

In [ ]:
e[0][0]

1

In [ ]:
e[0,0]

TypeError: ignored

In [ ]:
e.shape

AttributeError: ignored

In [ ]:
2*d

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
n = np.dot(d,b)
n

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [ ]:
n + n

array([[ 18,  24,  30],
       [ 38,  52,  66],
       [ 58,  80, 102]])

In [ ]:
[1, 1., 'sss', {1:'f'}]

[1, 1.0, 'sss', {1: 'f'}]

In [ ]:
np.sin(n)

array([[ 0.41211849, -0.53657292,  0.65028784],
       [ 0.14987721,  0.76255845,  0.99991186],
       [-0.66363388,  0.74511316,  0.67022918]])

In [ ]:
v = {'ali':180, 'reza':175}
v

{'ali': 180, 'reza': 175}

In [ ]:
v['ali']

180

In [ ]:
v.keys()

dict_keys(['ali', 'reza'])

In [ ]:
v.values()

dict_values([180, 175])

In [ ]:
v = {180:'ali', 175:'reza'}
v

{175: 'reza', 180: 'ali'}

In [ ]:
v['reza']

KeyError: ignored

In [ ]:
v[175]

'reza'

In [ ]:
c = "abcd efgh"
c.split('b')

['a', 'cd efgh']

In [ ]:
n.mean()

26.0

In [ ]:
a = 5
b = 10
c = 10
d = b*b - 4*a*c
if d<=0:
  print('no solution')
else:
  x1 = (-b + (d)**0.5)/(2*a)
  x2 = (-b - (d)**0.5)/(2*a)
  x = [x1, x2]

no solution


In [ ]:
x

[-0.10050506338833429, -19.899494936611667]

In [ ]:
a = input('enter a value')
a = int(a)
if a%2==0:
  print('a is even number')
else:
  print('a is odd numer')

enter a value11
a is odd numer


In [ ]:
bmi = input('Enter your bmi: ')
bmi = float(bmi)
if bmi<=25:
  print('so healthy')
elif bmi>25 and bmi<=30:
  print('conduct more exercise')
else:
  print('very bad')

Enter your bmi: 31
veryc bad


In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
not True

False

In [ ]:
not False

True