<a href="https://colab.research.google.com/github/MJavadZallaghi/itmemaut/blob/main/itmemaut3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = [0, 0, 1, 4, 7, 16, 31, 64, 127]

In [ ]:
b = np.array(a)

In [ ]:
b

array([  0,   0,   1,   4,   7,  16,  31,  64, 127])

In [ ]:
c = np.array([1, 4., -2, 7])
c

array([ 1.,  4., -2.,  7.])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.logspace(1,3,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0.,10,2)

array([0., 2., 4., 6., 8.])

In [ ]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [ ]:
np.arange(0.,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
2*np.ones(8, dtype=int)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
a = np.linspace(-1,5,7)

In [ ]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [ ]:
a*6

array([-6.,  0.,  6., 12., 18., 24., 30.])

In [ ]:
a/5

array([-0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [ ]:
a**3

array([ -1.,   0.,   1.,   8.,  27.,  64., 125.])

In [ ]:
a+4

array([3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a-10

array([-11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.])

In [ ]:
(a+3)*2

array([ 4.,  6.,  8., 10., 12., 14., 16.])

In [ ]:
np.sin(a)

array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
       -0.7568025 , -0.95892427])

In [ ]:
np.exp(-a) #array([e^1 e^0 e^-1 ...])

array([2.71828183, 1.        , 0.36787944, 0.13533528, 0.04978707,
       0.01831564, 0.00673795])

In [ ]:
b = 5*np.ones(8)

In [ ]:
b

array([5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
b += 4

In [ ]:
b

array([9., 9., 9., 9., 9., 9., 9., 9.])

In [ ]:
# y = cos(x)
x = np.linspace(-np.pi, np.pi, 21)
y = np.cos(x)

In [ ]:
x

array([-3.14159265, -2.82743339, -2.51327412, -2.19911486, -1.88495559,
       -1.57079633, -1.25663706, -0.9424778 , -0.62831853, -0.31415927,
        0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339,
        3.14159265])

In [ ]:
y

array([-1.00000000e+00, -9.51056516e-01, -8.09016994e-01, -5.87785252e-01,
       -3.09016994e-01,  6.12323400e-17,  3.09016994e-01,  5.87785252e-01,
        8.09016994e-01,  9.51056516e-01,  1.00000000e+00,  9.51056516e-01,
        8.09016994e-01,  5.87785252e-01,  3.09016994e-01,  6.12323400e-17,
       -3.09016994e-01, -5.87785252e-01, -8.09016994e-01, -9.51056516e-01,
       -1.00000000e+00])

In [ ]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [ ]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([       nan,       -inf, 0.        , 0.69314718, 1.09861229,
       1.38629436, 1.60943791])

In [ ]:
a = np.array([34.,-12,5])

In [ ]:
b = np.array([68.,5,20])

In [ ]:
a+b

array([102.,  -7.,  25.])

In [ ]:
a*b

array([2312.,  -60.,  100.])

In [ ]:
a/b

array([ 0.5 , -2.4 ,  0.25])

In [ ]:
m = np.array([2,2])

In [ ]:
a+m

ValueError: ignored

In [ ]:
y = np.array([0., 1.3, 5., 10.9, 18.9, 28.7, 40.])

In [ ]:
t = np.array([0., 0.49, 1., 1.5, 2.08, 2.55, 3.2])

In [ ]:
# v = (y_i - y_i_1)/(t_i - t_i_1)

In [ ]:
y[:-1]

array([ 0. ,  1.3,  5. , 10.9, 18.9, 28.7])

In [ ]:
y[1:]

array([ 1.3,  5. , 10.9, 18.9, 28.7, 40. ])

In [ ]:
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])

In [ ]:
v

array([ 2.65306122,  7.25490196, 11.8       , 13.79310345, 20.85106383,
       17.38461538])

In [ ]:
b = 1.0/np.arange(0.2,3,0.2)

In [ ]:
b

array([5.        , 2.5       , 1.66666667, 1.25      , 1.        ,
       0.83333333, 0.71428571, 0.625     , 0.55555556, 0.5       ,
       0.45454545, 0.41666667, 0.38461538, 0.35714286])

In [ ]:
b[b>1]

array([5.        , 2.5       , 1.66666667, 1.25      ])

In [ ]:
b[b>1] = 1

In [ ]:
b

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.83333333, 0.71428571, 0.625     , 0.55555556, 0.5       ,
       0.45454545, 0.41666667, 0.38461538, 0.35714286])

In [ ]:
b.size

14

In [ ]:
c = np.linspace(0,10,b.size)

In [ ]:
c

array([ 0.        ,  0.76923077,  1.53846154,  2.30769231,  3.07692308,
        3.84615385,  4.61538462,  5.38461538,  6.15384615,  6.92307692,
        7.69230769,  8.46153846,  9.23076923, 10.        ])

In [ ]:
c[b==1]=3

In [ ]:
c

array([ 3.        ,  3.        ,  3.        ,  3.        ,  3.        ,
        3.84615385,  4.61538462,  5.38461538,  6.15384615,  6.92307692,
        7.69230769,  8.46153846,  9.23076923, 10.        ])

In [ ]:
y = np.sin(np.linspace(0,4*np.pi, 9))

In [ ]:
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16,  1.0000000e+00,  3.6739404e-16, -1.0000000e+00,
       -4.8985872e-16])

In [ ]:
y[np.abs(y)<1.0e-15]=0

In [ ]:
y

array([ 0.,  1.,  0., -1.,  0.,  1.,  0., -1.,  0.])